In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier,RandomForestRegressor 
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report, confusion_matrix ,accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression

In [3]:
df = pd.read_csv(r"C:\Users\ADMIN\Downloads\used_phone_price_prediction_1M.csv")

In [4]:
df.head()

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score,resale_price
0,Realme,Realme GT,2025,4,256,6.93,4130,47,100,Android,...,0,0,0,Tier1,Individual,11,1,1,99,47891.46
1,Samsung,Galaxy S21,2024,16,64,6.29,5558,81,67,Android,...,0,0,0,Tier3,Store,8,1,0,64,17663.21
2,Apple,iPhone 11,2022,4,128,5.52,5945,59,67,iOS,...,0,0,0,Tier1,Individual,0,0,1,68,67268.20
3,Google,Pixel 6,2024,16,512,5.99,5767,84,57,Android,...,0,0,1,Tier1,Store,11,1,1,50,12626.26
4,Google,Pixel 7,2021,4,128,6.59,5336,98,44,Android,...,0,0,0,Tier3,Store,24,1,1,66,20662.25

In [5]:
df.isna().sum()

brand                        0
model                        0
release_year                 0
ram_gb                       0
storage_gb                   0
screen_size_inches           0
battery_capacity             0
processor_score              0
camera_score                 0
os_type                      0
has_5g                       0
original_price               0
purchase_year                0
age_months                   0
usage_hours_per_day          0
condition                    0
battery_health               0
screen_cracked               0
body_damage                  0
repair_history               0
water_damage                 0
city_tier                    0
seller_type                  0
warranty_remaining_months    0
box_available                0
charger_available            0
market_demand_score          0
resale_price                 0
dtype: int64

In [6]:
df.dtypes

brand                         object
model                         object
release_year                   int64
ram_gb                         int64
storage_gb                     int64
screen_size_inches           float64
battery_capacity               int64
processor_score                int64
camera_score                   int64
os_type                       object
has_5g                         int64
original_price                 int64
purchase_year                  int64
age_months                     int64
usage_hours_per_day          float64
condition                     object
battery_health                 int64
screen_cracked                 int64
body_damage                    int64
repair_history                 int64
water_damage                   int64
city_tier                     object
seller_type                   object
warranty_remaining_months      int64
box_available                  int64
charger_available              int64
market_demand_score            int64
resale_price                 float64
dtype: object

In [7]:
x = df.drop(columns=['resale_price'])

In [8]:
x

,brand,model,release_year,ram_gb,storage_gb,screen_size_inches,battery_capacity,processor_score,camera_score,os_type,...,screen_cracked,body_damage,repair_history,water_damage,city_tier,seller_type,warranty_remaining_months,box_available,charger_available,market_demand_score
0,Realme,Realme GT,2025,4,256,6.93,4130,47,100,Android,...,0,0,0,0,Tier1,Individual,11,1,1,99
1,Samsung,Galaxy S21,2024,16,64,6.29,5558,81,67,Android,...,0,0,0,0,Tier3,Store,8,1,0,64
2,Apple,iPhone 11,2022,4,128,5.52,5945,59,67,iOS,...,0,0,0,0,Tier1,Individual,0,0,1,68
3,Google,Pixel 6,2024,16,512,5.99,5767,84,57,Android,...,0,0,0,1,Tier1,Store,11,1,1,50
4,Google,Pixel 7,2021,4,128,6.59,5336,98,44,Android,...,0,0,0,0,Tier3,Store,24,1,1,66
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,Samsung,Galaxy A54,2023,6,128,6.61,6358,99,63,Android,...,0,0,0,0,Tier3,Store,11,1,1,95
999996,Samsung,Galaxy A54,2021,16,512,6.19,6142,63,43,Android,...,0,0,0,0,Tier3,Store,11,0,1,65
999997,Apple,iPhone 15,2022,4,256,5.97,5874,79,49,iOS,...,0,0,0,0,Tier2,Individual,14,0,1,99
999998,Apple,iPhone 13,2023,12,512,6.73,5220,53,56,iOS,...,0,0,0,0,Tier3,Store,17,1,1,57
999999,Realme,Realme GT,2020,16,256,6.16,6463,91,51,Android,...,0,0,1,0,Tier2,Individual,10,1,1,83

In [27]:
y = df['resale_price']

In [28]:
col = ['brand' , 'model' ,'os_type' , 'city_tier' , 'seller_type','condition']

le = LabelEncoder()
for columns  in col :
    x[columns] =le.fit_transform(x[columns])

In [29]:
y = le.fit_transform(y)

In [12]:
X =x[:10000]
y =y[:10000]

In [30]:
x.size

27000000

In [31]:
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2 ,random_state=42)

In [15]:
x_train.size

216000

In [16]:
y

array([799579, 394253, 858403, ..., 479380,  80704, 340488],
      shape=(10000,))

In [17]:
x_test.size

54000

In [18]:
x_train.dtypes

brand                          int64
model                          int64
release_year                   int64
ram_gb                         int64
storage_gb                     int64
screen_size_inches           float64
battery_capacity               int64
processor_score                int64
camera_score                   int64
os_type                        int64
has_5g                         int64
original_price                 int64
purchase_year                  int64
age_months                     int64
usage_hours_per_day          float64
condition                      int64
battery_health                 int64
screen_cracked                 int64
body_damage                    int64
repair_history                 int64
water_damage                   int64
city_tier                      int64
seller_type                    int64
warranty_remaining_months      int64
box_available                  int64
charger_available              int64
market_demand_score            int64
dtype: object

In [19]:
scale = StandardScaler()
x_train = scale.fit_transform(x_train)
x_test = scale.transform(x_test)

In [20]:
Model1 =RandomForestRegressor(random_state = 42 , n_estimators=100)

In [21]:
Model1.fit(x_train, y_train)

RandomForestRegressor(random_state=42)

In [22]:
y_pred = Model1.predict(x_test)

In [25]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [23]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Calculate regression metrics
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Regression Evaluation Report")
print("-" * 30)
print(f"Mean Absolute Error (MAE) : {mae:.4f}")
print(f"Mean Squared Error (MSE)   : {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared Score (R²)      : {r2:.4f}")

Regression Evaluation Report
------------------------------
Mean Absolute Error (MAE) : 62338.5378
Mean Squared Error (MSE)   : 6390914420.0087
Root Mean Squared Error (RMSE): 79943.1950
R-squared Score (R²)      : 0.8990

In [24]:
reg_model = LinearRegression()
reg_model.fit(x_train, y_train)

LinearRegression()

In [25]:
y_pred = reg_model.predict(x_test)

In [26]:
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Regression Evaluation Report")
print("-" * 30)
print(f"Mean Absolute Error (MAE) : {mae:.4f}")
print(f"Mean Squared Error (MSE)   : {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared Score (R²)      : {r2:.4f}")

Regression Evaluation Report
------------------------------
Mean Absolute Error (MAE) : 71057.2273
Mean Squared Error (MSE)   : 7884776476.7673
Root Mean Squared Error (RMSE): 88796.2639
R-squared Score (R²)      : 0.8753

In [21]:
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split, RandomizedSearchCV

In [28]:
xgb = XGBRegressor(
    objective='reg:squarederror', 
    random_state=42, 
    n_jobs=-1
)

In [58]:
bg=xgb.fit(x_train, y_train)
y_pred = bg.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Regression Evaluation Report")
print("-" * 30)
print(f"Mean Absolute Error (MAE) : {mae:.4f}")
print(f"Mean Squared Error (MSE)   : {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared Score (R²)      : {r2:.4f}")

Regression Evaluation Report
------------------------------
Mean Absolute Error (MAE) : 44415.4961
Mean Squared Error (MSE)   : 3309746688.0000
Root Mean Squared Error (RMSE): 57530.3979
R-squared Score (R²)      : 0.9477

In [22]:
param_distributions = {
    'n_estimators': [100, 200, 300, 500],
    'learning_rate': [0.01, 0.03, 0.05, 0.1, 0.2],
    'max_depth': [3, 5, 7, 9, 11],
    'subsample': [0.6, 0.7, 0.8, 0.9, 1.0],
    'colsample_bytree': [0.6, 0.7, 0.8, 0.9, 1.0],
}

xgb = XGBRegressor(
    objective='reg:squarederror', 
    random_state=42, 
    n_jobs=-1
)

xgb_random = RandomizedSearchCV(
    estimator=xgb,
    param_distributions=param_distributions,
    n_iter=50,
    scoring='neg_mean_squared_error',
    cv=5,
    verbose=1,
    random_state=42,
    n_jobs=-1
)

# 8. Fit on training set
xgb_random.fit(x_train, y_train)

# 9. Evaluate Best Model
best_xgb = xgb_random.best_estimator_
y_pred = best_xgb.predict(x_test)

print("Best Parameters:", xgb_random.best_params_)
print("Test RMSE:", np.sqrt(mean_squared_error(y_test, y_pred)))
print("Test R² Score:", r2_score(y_test, y_pred))

Fitting 5 folds for each of 50 candidates, totalling 250 fits
Best Parameters: {'subsample': 0.6, 'n_estimators': 200, 'max_depth': 5, 'learning_rate': 0.1, 'colsample_bytree': 0.8}

NameError: name 'mean_squared_error' is not defined

In [23]:
import xgboost as xgb

In [33]:

xgb_model = xgb.XGBRegressor(
    n_estimators=500,
    max_depth=8,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

In [34]:
bg=xgb_model.fit(x_train, y_train)
y_pred = bg.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Regression Evaluation Report")
print("-" * 30)
print(f"Mean Absolute Error (MAE) : {mae:.4f}")
print(f"Mean Squared Error (MSE)   : {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared Score (R²)      : {r2:.4f}")

Regression Evaluation Report
------------------------------
Mean Absolute Error (MAE) : 32561.0078
Mean Squared Error (MSE)   : 1865681152.0000
Root Mean Squared Error (RMSE): 43193.5314
R-squared Score (R²)      : 0.9716

In [32]:
bg=xgb_model.fit(x_train, y_train)
y_pred = bg.predict(x_test)

mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
mae = mean_absolute_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Regression Evaluation Report")
print("-" * 30)
print(f"Mean Absolute Error (MAE) : {mae:.4f}")
print(f"Mean Squared Error (MSE)   : {mse:.4f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.4f}")
print(f"R-squared Score (R²)      : {r2:.4f}")

Regression Evaluation Report
------------------------------
Mean Absolute Error (MAE) : 35942.0273
Mean Squared Error (MSE)   : 2149628160.0000
Root Mean Squared Error (RMSE): 46364.0827
R-squared Score (R²)      : 0.9673